import React, { useState } from 'react';
import { X, Plus, Trash2, Edit2, Save, Download, Copy, Check, Settings, Image as ImageIcon, DollarSign, RotateCcw } from 'lucide-react';
import { CatalogItem, ItemCategory, OwnerConfig } from '../types';

interface AdminManagerModalProps {
  isOpen: boolean;
  onClose: () => void;
  items: CatalogItem[];
  ownerConfig: OwnerConfig;
  onUpdateItems: (newItems: CatalogItem[]) => void;
  onUpdateOwnerConfig: (newConfig: OwnerConfig) => void;
  onResetToDefaults: () => void;
}

export const AdminManagerModal: React.FC<AdminManagerModalProps> = ({
  isOpen,
  onClose,
  items,
  ownerConfig,
  onUpdateItems,
  onUpdateOwnerConfig,
  onResetToDefaults,
}) => {
  if (!isOpen) return null;

  const [editingItemId, setEditingItemId] = useState<string | null>(null);
  const [itemsState, setItemsState] = useState<CatalogItem[]>([...items]);
  const [configState, setConfigState] = useState<OwnerConfig>({ ...ownerConfig });
  const [copiedCode, setCopiedCode] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);

  // New Item Form state
  const [newItem, setNewItem] = useState<Partial<CatalogItem>>({
    title: '',
    subtitle: '',
    description: '',
    category: 'apparel',
    supportsSplit: true,
    bridePrice: 25.0,
    bridesmaidPrice: 20.0,
    unitLabel: 'por unidad',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800',
    badge: 'Nuevo',
  });

  const handleSaveItemEdit = (id: string, updated: Partial<CatalogItem>) => {
    const next = itemsState.map((it) => (it.id === id ? { ...it, ...updated } : it));
    setItemsState(next);
    onUpdateItems(next);
    setEditingItemId(null);
  };

  const handleDeleteItem = (id: string) => {
    if (confirm('¿Estás segura de que deseas eliminar este artículo de tu catálogo?')) {
      const next = itemsState.filter((it) => it.id !== id);
      setItemsState(next);
      onUpdateItems(next);
    }
  };

  const handleAddNewItem = () => {
    if (!newItem.title || !newItem.imageUrl) {
      alert('Por favor proporciona un título y la URL de la imagen.');
      return;
    }

    const created: CatalogItem = {
      id: 'custom-' + Date.now(),
      title: newItem.title,
      subtitle: newItem.subtitle || '',
      description: newItem.description || '',
      category: newItem.category as ItemCategory,
      supportsSplit: !!newItem.supportsSplit,
      bridePrice: Number(newItem.bridePrice) || 0,
      bridesmaidPrice: Number(newItem.bridesmaidPrice) || 0,
      unitLabel: newItem.unitLabel || 'por unidad',
      imageUrl: newItem.imageUrl,
      badge: newItem.badge || undefined,
    };

    const next = [created, ...itemsState];
    setItemsState(next);
    onUpdateItems(next);
    setShowAddForm(false);
    setNewItem({
      title: '',
      subtitle: '',
      description: '',
      category: 'apparel',
      supportsSplit: true,
      bridePrice: 25.0,
      bridesmaidPrice: 20.0,
      unitLabel: 'por unidad',
      imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=800',
    });
  };

  const handleSaveConfig = () => {
    onUpdateOwnerConfig(configState);
    alert('¡Ajustes del negocio actualizados correctamente!');
  };

  const generateTsCode = () => {
    return `// Updated catalog items generated by Nostalgia Catalog Manager
export const INITIAL_ITEMS = ${JSON.stringify(itemsState, null, 2)};
`;
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generateTsCode());
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-[#FFFDFB] rounded-sm max-w-4xl w-full nostalgic-border shadow-2xl p-6 sm:p-8 space-y-6 relative my-8 max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex justify-between items-start border-b border-[#8C786A]/20 pb-4">
          <div>
            <div className="flex items-center gap-2 text-[#8C786A] text-xs uppercase tracking-widest font-semibold">
              <Settings className="w-4 h-4" /> Administrador del Catálogo
            </div>
            <h2 className="serif text-2xl font-bold text-[#3A3530]">
              Editar Precios, Productos y Fotos
            </h2>
            <p className="text-xs text-[#8C786A]">
              Los cambios se aplican en vivo de inmediato. También puedes copiar el código TypeScript generado para <code className="bg-[#EFE8E1] px-1 py-0.5 rounded-xs font-mono">/src/data/items.ts</code>.
            </p>
          </div>

          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-[#EFE8E1] hover:bg-[#E4D9CE] text-[#3A3530] flex items-center justify-center transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Business Settings */}
        <div className="bg-[#F9F7F2] p-4 rounded-xs border border-[#8C786A]/20 space-y-3 text-xs">
          <h3 className="font-bold text-[#3A3530] uppercase tracking-wider flex items-center gap-2">
            <DollarSign className="w-3.5 h-3.5 text-[#8C786A]" /> Ajustes del Negocio y Contacto
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Número de WhatsApp</label>
              <input
                type="text"
                value={configState.whatsappNumber}
                onChange={(e) => setConfigState({ ...configState, whatsappNumber: e.target.value })}
                className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs font-mono"
              />
            </div>

            <div>
              <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Usuario de Instagram</label>
              <input
                type="text"
                value={configState.instagramHandle}
                onChange={(e) => setConfigState({ ...configState, instagramHandle: e.target.value })}
                className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs font-mono"
              />
            </div>

            <div>
              <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Correo de Contacto</label>
              <input
                type="email"
                value={configState.contactEmail}
                onChange={(e) => setConfigState({ ...configState, contactEmail: e.target.value })}
                className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs font-mono"
              />
            </div>
          </div>
          <div className="flex justify-end">
            <button
              onClick={handleSaveConfig}
              className="px-3 py-1.5 btn-primary rounded-xs text-[10px] uppercase font-bold cursor-pointer"
            >
              Guardar Ajustes
            </button>
          </div>
        </div>

        {/* Action bar for catalog */}
        <div className="flex justify-between items-center pt-2">
          <button
            onClick={() => setShowAddForm(!showAddForm)}
            className="px-3.5 py-2 btn-primary rounded-xs text-xs uppercase tracking-wider font-bold flex items-center gap-2 cursor-pointer shadow-xs"
          >
            <Plus className="w-4 h-4" /> {showAddForm ? 'Cancelar Nuevo Artículo' : 'Agregar Nuevo Artículo al Catálogo'}
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={onResetToDefaults}
              className="px-3 py-2 btn-secondary rounded-xs text-[11px] uppercase tracking-wider font-semibold flex items-center gap-1.5 cursor-pointer text-[#8C786A]"
              title="Restablecer lista de productos original"
            >
              <RotateCcw className="w-3.5 h-3.5" /> Restablecer
            </button>

            <button
              onClick={handleCopyCode}
              className="px-3 py-2 bg-[#EFE8E1] hover:bg-[#E4D9CE] text-[#3A3530] border border-[#8C786A]/30 rounded-xs text-[11px] uppercase tracking-wider font-semibold flex items-center gap-1.5 cursor-pointer"
            >
              {copiedCode ? <Check className="w-3.5 h-3.5 text-green-700" /> : <Copy className="w-3.5 h-3.5 text-[#8C786A]" />}
              {copiedCode ? '¡Código Copiado!' : 'Exportar / Copiar Código'}
            </button>
          </div>
        </div>

        {/* Add New Item Form */}
        {showAddForm && (
          <div className="bg-[#F8ECE8] p-4 rounded-xs border border-[#8C786A]/30 space-y-3 text-xs animate-in fade-in duration-150">
            <h4 className="font-bold text-[#3A3530] uppercase tracking-wider">Crear Nuevo Producto en Catálogo</h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Título del Artículo *</label>
                <input
                  type="text"
                  value={newItem.title}
                  onChange={(e) => setNewItem({ ...newItem, title: e.target.value })}
                  placeholder="ej. Batas de Seda Personalizadas"
                  className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs"
                />
              </div>

              <div>
                <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Subtítulo</label>
                <input
                  type="text"
                  value={newItem.subtitle}
                  onChange={(e) => setNewItem({ ...newItem, subtitle: e.target.value })}
                  placeholder="ej. Batas para la Novia y Damas"
                  className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs"
                />
              </div>

              <div>
                <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">URL de la Imagen *</label>
                <input
                  type="text"
                  value={newItem.imageUrl}
                  onChange={(e) => setNewItem({ ...newItem, imageUrl: e.target.value })}
                  placeholder="https://images.unsplash.com/..."
                  className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs font-mono"
                />
              </div>

              <div>
                <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Categoría</label>
                <select
                  value={newItem.category}
                  onChange={(e) => setNewItem({ ...newItem, category: e.target.value as ItemCategory })}
                  className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs"
                >
                  <option value="apparel">Prendas y Outfits</option>
                  <option value="drinkware">Termos y Vasos</option>
                  <option value="inside-jokes">Chistes Locales y Props</option>
                  <option value="decor-and-accessories">Decoración y Accesorios</option>
                  <option value="party-kits">Kits Completo & Cajas</option>
                </select>
              </div>

              <div>
                <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Precio Versión Novia ($)</label>
                <input
                  type="number"
                  step="0.5"
                  value={newItem.bridePrice}
                  onChange={(e) => setNewItem({ ...newItem, bridePrice: parseFloat(e.target.value) || 0 })}
                  className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs font-mono font-bold"
                />
              </div>

              <div>
                <label className="text-[10px] text-[#8C786A] uppercase font-bold block mb-1">Precio Versión Damas ($)</label>
                <input
                  type="number"
                  step="0.5"
                  value={newItem.bridesmaidPrice}
                  onChange={(e) => setNewItem({ ...newItem, bridesmaidPrice: parseFloat(e.target.value) || 0 })}
                  className="w-full p-2 bg-white border border-[#8C786A]/30 rounded-xs text-xs font-mono font-bold"
                />
              </div>
            </div>

            <div className="flex items-center gap-4">
              <label className="flex items-center gap-2 cursor-pointer text-xs font-semibold text-[#3A3530]">
                <input
                  type="checkbox"
                  checked={newItem.supportsSplit}
                  onChange={(e) => setNewItem({ ...newItem, supportsSplit: e.target.checked })}
                />
                Diferenciar Precios y Cantidades entre Novia y Damas
              </label>
            </div>

            <button
              onClick={handleAddNewItem}
              className="w-full py-2.5 btn-primary rounded-xs text-xs uppercase font-bold"
            >
              Guardar Nuevo Artículo
            </button>
          </div>
        )}

        {/* Existing Items Editable List */}
        <div className="flex-1 overflow-y-auto space-y-3 pr-2">
          {itemsState.map((it) => (
            <div
              key={it.id}
              className="p-4 bg-white rounded-xs border border-[#8C786A]/20 hover:border-[#8C786A]/50 space-y-3 text-xs"
            >
              <div className="flex justify-between items-start gap-4">
                <img
                  src={it.imageUrl}
                  alt={it.title}
                  referrerPolicy="no-referrer"
                  className="w-14 h-14 object-cover rounded-xs border border-[#8C786A]/20"
                />

                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <h4 className="font-bold text-[#3A3530] text-sm">{it.title}</h4>
                    <span className="text-[9px] uppercase font-mono px-2 py-0.5 bg-[#EFE8E1] rounded-xs text-[#8C786A]">
                      {it.category}
                    </span>
                  </div>
                  <p className="text-[11px] text-[#8C786A] italic">{it.subtitle}</p>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setEditingItemId(editingItemId === it.id ? null : it.id)}
                    className="p-1.5 rounded-xs bg-[#EFE8E1] hover:bg-[#E4D9CE] text-[#3A3530] cursor-pointer"
                    title="Editar Artículo"
                  >
                    <Edit2 className="w-3.5 h-3.5 text-[#8C786A]" />
                  </button>

                  <button
                    onClick={() => handleDeleteItem(it.id)}
                    className="p-1.5 rounded-xs bg-red-50 hover:bg-red-100 text-red-700 cursor-pointer"
                    title="Eliminar Artículo"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Editable Fields row */}
              {editingItemId === it.id ? (
                <div className="pt-3 border-t border-dashed border-[#8C786A]/20 space-y-3 bg-[#F9F7F2] p-3 rounded-xs">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div>
                      <label className="text-[9px] font-bold uppercase text-[#8C786A]">Título</label>
                      <input
                        type="text"
                        defaultValue={it.title}
                        onBlur={(e) => handleSaveItemEdit(it.id, { title: e.target.value })}
                        className="w-full p-1.5 bg-white border border-[#8C786A]/30 text-xs rounded-xs"
                      />
                    </div>

                    <div>
                      <label className="text-[9px] font-bold uppercase text-[#8C786A]">URL de Imagen</label>
                      <input
                        type="text"
                        defaultValue={it.imageUrl}
                        onBlur={(e) => handleSaveItemEdit(it.id, { imageUrl: e.target.value })}
                        className="w-full p-1.5 bg-white border border-[#8C786A]/30 text-xs font-mono rounded-xs"
                      />
                    </div>

                    <div>
                      <label className="text-[9px] font-bold uppercase text-[#8C786A]">Precio Novia ($)</label>
                      <input
                        type="number"
                        step="0.5"
                        defaultValue={it.bridePrice}
                        onBlur={(e) =>
                          handleSaveItemEdit(it.id, { bridePrice: parseFloat(e.target.value) || 0 })
                        }
                        className="w-full p-1.5 bg-white border border-[#8C786A]/30 text-xs font-mono font-bold rounded-xs"
                      />
                    </div>

                    <div>
                      <label className="text-[9px] font-bold uppercase text-[#8C786A]">Precio Damas ($)</label>
                      <input
                        type="number"
                        step="0.5"
                        defaultValue={it.bridesmaidPrice}
                        onBlur={(e) =>
                          handleSaveItemEdit(it.id, { bridesmaidPrice: parseFloat(e.target.value) || 0 })
                        }
                        className="w-full p-1.5 bg-white border border-[#8C786A]/30 text-xs font-mono font-bold rounded-xs"
                      />
                    </div>
                  </div>

                  <div className="flex justify-end">
                    <button
                      onClick={() => setEditingItemId(null)}
                      className="px-3 py-1 btn-primary text-[10px] uppercase font-bold rounded-xs cursor-pointer"
                    >
                      Listo
                    </button>
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-between text-[11px] text-[#8C786A] pt-1 font-mono border-t border-dashed border-[#8C786A]/10">
                  <span>
                    Precio Novia: <strong>${it.bridePrice.toFixed(2)}</strong> | Precio Damas: <strong>${it.bridesmaidPrice.toFixed(2)}</strong>
                  </span>
                  <span>Diferenciado: {it.supportsSplit ? 'Sí' : 'No (Precio Fijo)'}</span>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
